name: Finy my doctors

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch: # manual trigger

env:
  DOCTOR_DATA_FILE: doctor_data.json

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "MEDICOVER_USER=${{ secrets.MEDICOVER_USER }}" > ./mediApp/.env
          echo "MEDICOVER_PASS=${{ secrets.MEDICOVER_PASS }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_ID }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> ./mediApp/.env
          
      - name: Build Docker image (mediczuwacz)
        run: docker build --rm -t mediczuwacz ./mediApp

      - name: Download doctor data artifact (if exists)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: doctor_data
          path: ./shared

      - name: Run specialist
        run: python ./mediApp/run_task.py
      
      # - name: Run sickness Czerwone Maki
      #   run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-05-30" -e "2025-05-30" -c 91164
        
      # - name: Run sickness Fabryczna
      #   run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-05-30" -e "2025-05-30" -c 102436

      # - name: Run sickness Podgórska
      #   run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-05-30" -e "2025-05-30" -c 13038

      - name: Upload updated doctor data
        uses: actions/upload-artifact@v4
        with:
          name: doctor_data
          path: ./shared/doctor_data.json
