name: Run My Docker App Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch: # manual trigger

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "MEDICOVER_USER=${{ secrets.MEDICOVER_USER }}" > ./mediApp/.env
          echo "MEDICOVER_PASS=${{ secrets.MEDICOVER_PASS }}" >> ./mediApp/.env
          
      - name: Build Docker image (mediczuwacz)
        run: docker build --rm -t mediczuwacz ./mediApp

      - name: Run the container
        run: docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 4798  -d 147484
