name: Run My Docker App Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "MEDICOVER_USER=${{ secrets.MEDICOVER_USER }}" > ./mediApp/.env
          echo "MEDICOVER_PASS=${{ secrets.MEDICOVER_PASS }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_ID }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> ./mediApp/.env
          
      - name: Build Docker image (mediczuwacz)
        run: docker build --rm -t mediczuwacz ./mediApp

      - name: Run tasks using Python
        run: python ./mediApp/run_task.py
