name: Finy my doctors

on:
  schedule:
    - cron: '0,15,30,45 4-22 * * *'
  workflow_dispatch: # manual trigger

permissions:
    contents: write

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "MEDICOVER_USER=${{ secrets.MEDICOVER_USER }}" > ./mediApp/.env
          echo "MEDICOVER_PASS=${{ secrets.MEDICOVER_PASS }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_ID }}" >> ./mediApp/.env
          echo "NOTIFIERS_TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> ./mediApp/.env
          
      - name: Build Docker image (mediczuwacz)
        run: docker build --rm -t mediczuwacz ./mediApp

      - name: Run specialist
        run: python ./mediApp/run_task.py

      #- name: Run sickness Czerwone Maki
        #run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-07-08" -e "2025-07-08" -c 91164
        
      #- name: Run sickness Fabryczna
        #run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-07-08" -e "2025-07-08" -c 102436

      #- name: Run sickness Podgórska
        #run:  docker run --rm --env-file=./mediApp/.env mediczuwacz find-appointment -r 202 -s 16234 -n telegram -f "2025-07-08" -e "2025-07-08" -c 13038
      
      - name: Commit and push updated doctor_data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add shared/doctor_data.json
          git commit -m "Update doctor data [bot]" || echo "Nothing to commit"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}